version: '3.8'
services:
  dotnet_postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Homeworks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dotnet_network
    
  dotnet_rabbitmq:
    image: rabbitmq:3-alpine
    environment:
      RABBITMQ_DEFAULT_USER: a1unade
      RABBITMQ_DEFAULT_PASS: a1unade
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - dotnet_network

  dotnet_minio:
    image: quay.io/minio/minio
    environment:
      MINIO_ROOT_USER: a1unade
      MINIO_ROOT_PASSWORD: a1unade
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - dotnet_network
    
  dotnet_mongodb:
    image: mongo:latest
    
  dotnet_jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
    environment:
      COLLECTOR_OTLP_ENABLED: true
    networks:
      - dotnet_network

  dotnet_main:
    image: dotnet-web
    build:
      context: .
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    depends_on:
      - dotnet_postgres
      - dotnet_rabbitmq
      - dotnet_jaeger
    environment:
        ASPNETCORE_URLS: "http://*:80"
        RabbitMqConfig__Username: "a1unade"
        RabbitMqConfig__Password: "a1unade"
        RabbitMqConfig__Hostname: "dotnet_rabbitmq:5672"
        ConnectionStrings__Default: "Host=dotnet_postgres;Port=5432;Username=postgres;Password=postgres;Database=Homeworks;"
        OpenTelemetryConfig__OtlpExporterEndpoint: "http://localhost:16686"
    ports:
      - "9000:80"
    networks:
      - dotnet_network
    
  dotnet_mailing:
    build:
      context: .
      dockerfile: Dotnet.Homeworks.Mailing.API/Dockerfile
    depends_on:
      - dotnet_rabbitmq
    environment:
      EmailConfig__Email: "jinx.httpserver@yandex.ru"
      EmailConfig__Host: "smtp.yandex.ru"
      EmailConfig__Port: "465"
      EmailConfig__Password: "kfgxrkizhidqhnyd"
      RabbitMqConfig__Username: "a1unade"
      RabbitMqConfig__Password: "a1unade"
      RabbitMqConfig__Hostname: "dotnet_rabbitmq:5672"
    networks:
      - dotnet_network
    
  dotnet_storage:
    image: dotnet-web
    build:
      context: .
      dockerfile: Dotnet.Homeworks.Storage.API/Dockerfile
    depends_on:
      - dotnet_minio
    ports:
      - "8082:8082"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://*:8082
      MinioConfig__Username: a1unade
      MinioConfig__Password: a1unade
      MinioConfig__Endpoint: dotnet_minio
      MinioConfig__Port: 9000
      MinioConfig__WithSsl: false
    networks:
      - dotnet_network
    
volumes:
  postgres_data:

networks:
  dotnet_network:
    driver: bridge