version: '3.8'
services:
  dotnet_postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Homeworks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dotnet_network
    
  dotnet_rabbitmq:
    image: rabbitmq:3-alpine
    environment:
      RABBITMQ_DEFAULT_USER: a1unade
      RABBITMQ_DEFAULT_PASS: a1unade
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - dotnet_network

  dotnet_minio:
    image: minio/minio:latest
    
  dotnet_mongodb:
    image: mongo:latest
    
  dotnet_jaeger:
    image: jaegertracing/all-in-one:latest
    
  dotnet_main:
    image: dotnet-web
    build:
      context: .
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    environment:
        ASPNETCORE_URLS: "http://*:80"
        RabbitMqConfig__Username: "a1unade"
        RabbitMqConfig__Password: "a1unade"
        RabbitMqConfig__Hostname: "dotnet_rabbitmq:5672"
        ConnectionStrings__Default: "Host=dotnet_postgres;Port=5432;Username=postgres;Password=postgres;Database=Homeworks;"
    ports:
      - "9000:80"
    depends_on:
      - dotnet_postgres
      - dotnet_rabbitmq
    networks:
      - dotnet_network
    
  dotnet_mailing:
    build:
      context: .
      dockerfile: Dotnet.Homeworks.Mailing.API/Dockerfile
    depends_on:
      - dotnet_rabbitmq
    environment:
      EmailConfig__Email: "jinx.httpserver@yandex.ru"
      EmailConfig__Host: "smtp.yandex.ru"
      EmailConfig__Port: "465"
      EmailConfig__Password: "kfgxrkizhidqhnyd"
      RabbitMqConfig__Username: "a1unade"
      RabbitMqConfig__Password: "a1unade"
      RabbitMqConfig__Hostname: "dotnet_rabbitmq:5672"
    networks:
      - dotnet_network
    
  dotnet_storage:
    image: dotnet-web
    
volumes:
  postgres_data:

networks:
  dotnet_network:
    driver: bridge